### ISSUE TITLE
USER STORY: Vote anonymously

### ISSUE THREAD

**Issue by GeorginaCarlisle** [GeorginaCarlisle/Walkthrough-LoveRunning#6]
In order to **protect my privacy when voting in the pole** as a **user** I can **vote anonymously**

## Acceptance Criteria
- option provide to add 'Anonymous' as the user name when completing the poll

## Tasks
- [ ] Using HTML add a checkbox to the poll form with the label "Set name as anonymous"
- [ ] Using JavaScript add function to set Username input the Anonymous when the checkbox is ticked
- [ ] Using CSS style the checkbox to align nicely within the poll container and meet any visual requirements
